services:
  patroni-1:
    image: postgres-cluster:latest
    container_name: patroni-1
    hostname: patroni-1
    volumes:
      - ./bootstrap.sh:/bootstrap.sh
      - ./patroni-1.yaml:/home/postgres/patroni.yml
      - etcd-1-data:/var/lib/etcd
      - patroni-1-data:/home/postgres/pgdata
    ports:
      - "5441:5432"
      - "8001:8008" #Patroni REST API.
    networks:
      - postgres-cluster

  patroni-2:
    image: postgres-cluster:latest
    container_name: patroni-2
    hostname: patroni-2
    volumes:
      - ./bootstrap.sh:/bootstrap.sh
      - ./patroni-2.yaml:/home/postgres/patroni.yml
      - etcd-2-data:/var/lib/etcd
      - patroni-2-data:/home/postgres/pgdata
    ports:
      - "5442:5432"
      - "8002:8008"
    networks:
      - postgres-cluster
    # depends_on:
    #   - patroni-1

  patroni-3:
    image: postgres-cluster:latest
    container_name: patroni-3
    hostname: patroni-3
    volumes:
      - ./bootstrap.sh:/bootstrap.sh
      - ./patroni-3.yaml:/home/postgres/patroni.yml
      - etcd-3-data:/var/lib/etcd
      - patroni-3-data:/home/postgres/pgdata
    ports:
      - "5443:5432"
      - "8003:8008"
    networks:
      - postgres-cluster
    # depends_on:
    #   - patroni-2

  haproxy:
    image: haproxy:2.8
    container_name: haproxy
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    ports:
      - "5432:5432"
      - "5433:5433"
      - "8404:8404" #HAProxy stats page.
    networks:
      - postgres-cluster
    depends_on:
      - patroni-1
      - patroni-2
      - patroni-3

volumes:
  patroni-1-data:
  patroni-2-data:
  patroni-3-data:
  etcd-1-data:
  etcd-2-data:
  etcd-3-data:

networks:
  postgres-cluster: